packages:
  - "packages/*"
  - "scripts"
  - "packages/playground/fixtures/**"
  - "packages/create-rspack/**"
  - "npm/*"
  - "crates/node_binding"
  - "crates/rspack_fs_node"
  - "crates/rspack_napi"
  - "examples/**"
  - "!examples/three"
  - "webpack-examples"
  - "benchcases/react-refresh"
  - "webpack-test"
  - "webpack-cli-test"
  - "diffcases/*"
